apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-httpd
  namespace: gitops-project
  labels:
    app: simple-httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-httpd
  template:
    metadata:
      labels:
        app: simple-httpd
    spec:
      containers:
      - name: httpd
        image: gadhittana01/simple-httpd:latest
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "50m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
