apiVersion: v1
kind: Service
metadata:
  name: simple-httpd-service
  namespace: argocd
  labels:
    app: simple-httpd
spec:
  type: ClusterIP
  selector:
    app: simple-httpd
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
