apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-service
  namespace: argocd
  labels:
    app: simple-nginx
spec:
  type: ClusterIP
  selector:
    app: simple-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
